#!/usr/bin/env python3
"""Generate src/il2cpp/slot_table_generated.rs from recon evidence.

The Global Android build of the game ships a hollowed libil2cpp.so (no il2cpp_*
exports; runtime dynamic section zeroed), so dlsym cannot resolve the il2cpp C API.
libunity.so contains a generated Il2CppApi compat layer instead: an init routine
resolves every il2cpp_* name through an internal resolver and stores the resulting
function pointers in a flat table inside libunity's BSS.

This script turns the extracted (name -> slot) mapping into a versioned Rust table
plus the build fingerprint used to validate the layout at runtime.

Inputs (defaults point at the recon workspace):
  --table    name_slot_table.txt   (index, name, name_string_vaddr, resolver_call_vaddr)
  --libunity libunity.so           (for the fingerprint bytes + file size)
Output:
  src/il2cpp/slot_table_generated.rs
"""
import argparse
import os

DEFAULT_RECON = r"C:\Users\Pure Fox\Documents\hachimi-global-recon"
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "src", "il2cpp", "slot_table_generated.rs")

# libunity ELF vaddr layout of the Il2CppApi layer (see recon notes / doc 320272ed)
TABLE_OFFSET = 0x12D1EE8      # base of the function-pointer table (234 * 8 bytes)
API_CTX_OFFSET = 0x12D2638    # context global, written just before the table is filled
INIT_FN_OFFSET = 0x653C3C     # init routine that fills the table
RESOLVER_OFFSET = 0x603050    # internal name -> pointer resolver
CODE_BIAS = 0x4000            # code segment: vaddr == file offset + 0x4000
FINGERPRINT_LEN = 16
# slots sampled at runtime to prove the layout before trusting the table
VALIDATION_SLOTS = [0, 1, 2, 40, 80, 120, 160, 200, 233]


def read_table(path):
    rows = []
    for line in open(path, encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 3 or parts[1] == "<MISSING>":
            continue
        rows.append((int(parts[0]), parts[1], int(parts[2], 16)))
    rows.sort(key=lambda r: r[0])
    return rows


def fingerprint(data, vaddr):
    off = vaddr - CODE_BIAS
    return data[off:off + FINGERPRINT_LEN]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--table", default=os.path.join(DEFAULT_RECON, "name_slot_table.txt"))
    ap.add_argument("--libunity", default=os.path.join(DEFAULT_RECON, "libunity.so"))
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--game-version", default="1.35.1")
    args = ap.parse_args()

    rows = read_table(args.table)
    if not rows:
        raise SystemExit("no rows parsed from %s" % args.table)
    slots = [r[0] for r in rows]
    if slots != list(range(len(rows))):
        raise SystemExit("slot indices are not contiguous 0..N-1: %r" % slots[:10])
    names = [r[1] for r in rows]
    if len(set(names)) != len(names):
        raise SystemExit("duplicate names in table")

    data = open(args.libunity, "rb").read()
    init_fp = fingerprint(data, INIT_FN_OFFSET)
    res_fp = fingerprint(data, RESOLVER_OFFSET)
    if len(init_fp) != FINGERPRINT_LEN or len(res_fp) != FINGERPRINT_LEN:
        raise SystemExit("could not read fingerprint bytes")

    out = []
    out.append("// @generated by tools/gen_il2cpp_slot_table.py -- do not edit by hand.")
    out.append("//")
    out.append("// Global Android il2cpp C-API slot table, extracted from libunity.so.")
    out.append("// Game build: %s   libunity.so size: %d bytes" % (args.game_version, len(data)))
    out.append("//")
    out.append("// The Global build hollows libil2cpp.so (no il2cpp_* exports, runtime dynsym")
    out.append("// zeroed) so dlsym cannot find the API. libunity.so instead carries a generated")
    out.append("// Il2CppApi compat layer: the routine at INIT_FN_OFFSET resolves every name via")
    out.append("// RESOLVER_OFFSET and stores the pointers at TABLE_OFFSET + slot*8. The")
    out.append("// fingerprints below pin that exact layout; add/carry a new table per game build.")
    out.append("")
    out.append("/// Base of the function-pointer table, relative to the libunity load address.")
    out.append("pub const TABLE_OFFSET: usize = 0x%x;" % TABLE_OFFSET)
    out.append("/// Number of entries in the table.")
    out.append("pub const SLOT_COUNT: usize = %d;" % len(rows))
    out.append("/// API context global, set by the init routine just before it fills the table.")
    out.append("pub const API_CTX_OFFSET: usize = 0x%x;" % API_CTX_OFFSET)
    out.append("/// Init routine that fills the table.")
    out.append("pub const INIT_FN_OFFSET: usize = 0x%x;" % INIT_FN_OFFSET)
    out.append("/// Internal name -> pointer resolver.")
    out.append("pub const RESOLVER_OFFSET: usize = 0x%x;" % RESOLVER_OFFSET)
    out.append("/// On-disk libunity.so size, for documentation/telemetry only.")
    out.append("pub const LIBUNITY_FILE_SIZE: u64 = %d;" % len(data))
    out.append("")
    out.append("/// First %d bytes of the init routine (layout fingerprint)." % FINGERPRINT_LEN)
    out.append("pub const INIT_FN_FINGERPRINT: [u8; %d] = [%s];"
               % (FINGERPRINT_LEN, ", ".join("0x%02x" % b for b in init_fp)))
    out.append("/// First %d bytes of the resolver (layout fingerprint)." % FINGERPRINT_LEN)
    out.append("pub const RESOLVER_FINGERPRINT: [u8; %d] = [%s];"
               % (FINGERPRINT_LEN, ", ".join("0x%02x" % b for b in res_fp)))
    out.append("")
    out.append("/// Slots sampled at runtime to prove the layout before the table is trusted.")
    out.append("pub const VALIDATION_SLOTS: [usize; %d] = [%s];"
               % (len(VALIDATION_SLOTS), ", ".join(str(s) for s in VALIDATION_SLOTS)))
    out.append("")
    out.append("/// One il2cpp C-API entry.")
    out.append("pub struct Slot {")
    out.append("    /// Function name as requested by the mod.")
    out.append("    pub name: &'static str,")
    out.append("    /// ELF vaddr of the bare name string in libunity rodata (layout check).")
    out.append("    pub name_off: usize,")
    out.append("    /// Index into the function-pointer table.")
    out.append("    pub slot: u16,")
    out.append("}")
    out.append("")
    out.append("/// Table contents in slot order.")
    out.append("pub static SLOTS: &[Slot] = &[")
    for idx, name, name_off in rows:
        out.append('    Slot { name: "%s", name_off: 0x%x, slot: %d },'
                   % (name, name_off, idx))
    out.append("];")
    out.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote %s (%d slots)" % (os.path.abspath(args.out), len(rows)))


if __name__ == "__main__":
    main()
